---
abstract: 'Mirror Configuration and Auto-Discovery'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  File::Temp: 0.19
  LWP::Online: 1.07
  Test::More: 0.42
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Mirror::YAML
name: Mirror-YAML
no_index:
  directory:
    - inc
    - t
requires:
  LWP::Simple: 0
  Params::Util: 0.25
  Parse::CPAN::Meta: 0.03
  Time::HiRes: 0
  Time::Local: 1.13
  URI: 1.28
  perl: 5.00503
resources:
  license: http://dev.perl.org/licenses/
version: 0.04_01
